version: "3.9"

services:
  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    ports:
      - "9000:9000"
    expose:
      - "9000"
    volumes:
      - ./app:/home/app

  mysql:
    env_file:
      - .env
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - php
    volumes:
      - ./app:/home/app
      - ./nginx/logs:/var/log/nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"